$(document).ready(function(){
			$('#b1').hide();
			$('#b2').hide();
			$('#b3').hide();
			$('#b4').hide();
			$('#data-company').hide();
			$('#hoverb1').mouseover(function(){
				$('#b1').show("slow");
			});
			$('#hoverb1').mouseleave(function(){
				$('#b1').hide("slow");
			});
			$('#hoverb2').mouseover(function(){
				$('#b2').show("slow");
			});
			$('#hoverb2').mouseleave(function(){
				$('#b2').hide("slow");
			});
			$('#hoverb3').mouseover(function(){
				$('#b3').show("slow");
			});
			$('#hoverb3').mouseleave(function(){
				$('#b3').hide("slow");
			});
			$('#hoverb4').mouseover(function(){
				$('#b4').show("slow");
			});
			$('#hoverb4').mouseleave(function(){
				$('#b4').hide("slow");
			});
			$('#text-input').click(function(){
				$('#data-company').show("slow");
			});
			$('#data-company').mouseleave(function(){
				$('#data-company').hide("slow");
			});
		});